version: '3.2'

services:
  elasticsearch:
    build:
      context: ./
    image: svnserver
    container_name: svnserver
#    volumes:
#      - type: bind
#        source: ./elasticsearch/config/elasticsearch.yml
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
#        read_only: true
#      - type: volume
#        source: elasticsearch
#        target: /usr/share/elasticsearch/data
    ports:
      - "80:80"
      - "443:443"
#    environment:
#      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - svn-net

networks:
  svn-net:
    driver: bridge
